import flights

# this class defines a flight timetable object which contains the departure city, arrival city,
#  and a list of Flights objects which contains the flights available from departure to arrival cities
class FlightTimeTable:
    departure_city = None
    arrival_city = None
    list_of_flights = None

    def __init__(self,departureCity,arrivalCity,listOfFlights):
        self.departure_city=departureCity
        self.arrival_city=arrivalCity
        self.list_of_flights=listOfFlights



def create_flight_plan():
    flightsList = flights.create_flights()
    flight_plan1 = FlightTimeTable("Alexandria", "Aswan", [flightsList[0], flightsList[1]])
    flight_plan2 = FlightTimeTable("Alexandria", "Cairo", [flightsList[2], flightsList[3], flightsList[4]])
    flight_plan3 = FlightTimeTable("Alexandria", "London", [flightsList[5]])
    flight_plan4 = FlightTimeTable("Alexandria", "New York", [flightsList[6]])
    flight_plan5 = FlightTimeTable("Aswan", "Cairo", [flightsList[7]])
    flight_plan6 = FlightTimeTable("Aswan", "Port Said", [flightsList[8]])
    flight_plan7 = FlightTimeTable("Cairo", "Alexandria", [flightsList[9], flightsList[10]])
    flight_plan8 = FlightTimeTable("Cairo", "Aswan", [flightsList[11], flightsList[12]])
    flight_plan9 = FlightTimeTable("Cairo", "London", [flightsList[13], flightsList[14]])
    flight_plan10 = FlightTimeTable("Cairo", "New York", [flightsList[15], flightsList[16]])
    flight_plan11 = FlightTimeTable("Cairo", "Paris", [flightsList[17], flightsList[18]])
    flight_plan12 = FlightTimeTable("Cairo", "Port Said", [flightsList[19], flightsList[20]])
    flight_plan13 = FlightTimeTable("Cairo", "Rome", [flightsList[21]])
    flight_plan14 = FlightTimeTable("Cairo", "Shanghai", [flightsList[22]])
    flight_plan15 = FlightTimeTable("Chicago", "London", [flightsList[23], flightsList[24]])
    flight_plan16 = FlightTimeTable("Chicago", "Miami", [flightsList[25], flightsList[26]])
    flight_plan17 = FlightTimeTable("Chicago", "New York", [flightsList[27], flightsList[28]])
    flight_plan18 = FlightTimeTable("Chicago", "Paris", [flightsList[29]])
    flight_plan19 = FlightTimeTable("Chicago", "San Francisco", [flightsList[30], flightsList[31]])
    flight_plan20 = FlightTimeTable("Edinburgh", "London", [flightsList[32], flightsList[33]])
    flight_plan21 = FlightTimeTable("Edinburgh", "Paris", [flightsList[34]])
    flight_plan22 = FlightTimeTable("Edinburgh", "San Francisco", [flightsList[35]])
    flight_plan23 = FlightTimeTable("Liverpool", "London", [flightsList[36], flightsList[37], flightsList[38]])
    flight_plan24 = FlightTimeTable("London", "Alexandria", [flightsList[39]])
    flight_plan25 = FlightTimeTable("London", "Cairo", [flightsList[40], flightsList[41]])
    flight_plan26 = FlightTimeTable("London", "Chicago", [flightsList[42]])
    flight_plan27 = FlightTimeTable("London", "Edinburgh", [flightsList[43], flightsList[44]])
    flight_plan28 = FlightTimeTable("London", "Liverpool", [flightsList[45], flightsList[46]])
    flight_plan29 = FlightTimeTable("London", "Lyon", [flightsList[47]])
    flight_plan31 = FlightTimeTable("London", "New York", [flightsList[50], flightsList[51]])
    flight_plan32 = FlightTimeTable("London", "Paris", [flightsList[52], flightsList[53]])
    flight_plan33 = FlightTimeTable("London", "Rome", [flightsList[54]])
    flight_plan34 = FlightTimeTable("London", "San Francisco", [flightsList[55]])
    flight_plan35 = FlightTimeTable("London", "Shanghai", [flightsList[56], flightsList[57]])
    flight_plan36 = FlightTimeTable("London", "Tokyo", [flightsList[58]])
    flight_plan37 = FlightTimeTable("Lyon", "Nice", [flightsList[59], flightsList[60]])
    flight_plan38 = FlightTimeTable("Lyon", "Paris", [flightsList[61], flightsList[62]])
    flight_plan39 = FlightTimeTable("Manchester", "London", [flightsList[63], flightsList[64]])
    flight_plan40 = FlightTimeTable("Miami", "Chicago", [flightsList[65]])
    flight_plan41 = FlightTimeTable("Miami", "New York", [flightsList[66], flightsList[67]])
    flight_plan42 = FlightTimeTable("Miami", "San Francisco", [flightsList[68]])
    flight_plan43 = FlightTimeTable("Milan", "London", [flightsList[69]])
    flight_plan44 = FlightTimeTable("Milan", "Paris", [flightsList[70], flightsList[71]])
    flight_plan45 = FlightTimeTable("Milan", "Rome", [flightsList[72], flightsList[73], flightsList[74]])
    flight_plan46 = FlightTimeTable("New York", "Chicago", [flightsList[75], flightsList[76]])
    flight_plan47 = FlightTimeTable("New York", "Edinburgh", [flightsList[77]])
    flight_plan48 = FlightTimeTable("New York", "London", [flightsList[78]])
    flight_plan49 = FlightTimeTable("New York", "Lyon", [flightsList[79]])
    flight_plan50 = FlightTimeTable("New York", "Miami", [flightsList[80], flightsList[81], flightsList[82]])
    flight_plan51 = FlightTimeTable("New York", "Paris", [flightsList[83]])
    flight_plan52 = FlightTimeTable("New York", "Rome", [flightsList[84]])
    flight_plan53 = FlightTimeTable("New York", "San Francisco",[flightsList[85], flightsList[86], flightsList[87], flightsList[88]])
    flight_plan54 = FlightTimeTable("New York", "Shanghai", [flightsList[89]])
    flight_plan55 = FlightTimeTable("New York", "Tokyo", [flightsList[90]])
    flight_plan56 = FlightTimeTable("Nice", "Lyon", [flightsList[91]])
    flight_plan57 = FlightTimeTable("Nice", "Paris", [flightsList[92], [flightsList[93]]])
    flight_plan58 = FlightTimeTable("Paris", "London", [flightsList[94], flightsList[95]])
    flight_plan59 = FlightTimeTable("Paris", "Lyon", [flightsList[96], flightsList[97]])
    flight_plan60 = FlightTimeTable("Paris", "New York", [flightsList[98], flightsList[99]])
    flight_plan61 = FlightTimeTable("Paris", "Nice", [flightsList[49]])
    flight_plan67 = FlightTimeTable("London", "Manchester", [flightsList[48]])
    flight_plan62 = FlightTimeTable("Paris", "Rome", [flightsList[101], flightsList[102]])
    flight_plan63 = FlightTimeTable("Paris", "Shanghai", [flightsList[103]])
    flight_plan64 = FlightTimeTable("Port Said", "Alexandria", [flightsList[104], flightsList[105]])
    flight_plan65 = FlightTimeTable("Port Said", "Cairo", [flightsList[106], flightsList[107]])
    flight_plan66 = FlightTimeTable("Rome", "London", [flightsList[108], flightsList[109]])
    flight_plan68 = FlightTimeTable("Rome", "Milan", [flightsList[110], flightsList[111]])
    flight_plan69 = FlightTimeTable("Rome", "New York", [flightsList[112], flightsList[113]])
    flight_plan70 = FlightTimeTable("Rome", "Paris", [flightsList[114], flightsList[115]])
    flight_plan71 = FlightTimeTable("Rome", "Venice", [flightsList[116], flightsList[117]])
    flight_plan72 = FlightTimeTable("San Francisco", "Chicago", [flightsList[118], flightsList[119]])
    flight_plan73 = FlightTimeTable("San Francisco", "Miami", [flightsList[120]])
    flight_plan74 = FlightTimeTable("San Francisco", "New York", [flightsList[121], flightsList[122]])
    flight_plan75 = FlightTimeTable("Shanghai", "Cairo", [flightsList[123], flightsList[124], flightsList[125]])
    flight_plan76 = FlightTimeTable("Shanghai", "Chicago", [flightsList[126], flightsList[127]])
    flight_plan77 = FlightTimeTable("Shanghai", "London", [flightsList[128], flightsList[129], flightsList[130]])
    flight_plan78 = FlightTimeTable("Shanghai", "New York", [flightsList[131], flightsList[132]])
    flight_plan79 = FlightTimeTable("Shanghai", "Paris", [flightsList[133], flightsList[134]])
    flight_plan80 = FlightTimeTable("Shanghai", "Rome", [flightsList[135], flightsList[136]])
    flight_plan81 = FlightTimeTable("Shanghai", "Tokyo", [flightsList[137], flightsList[138], flightsList[139], flightsList[140]])
    flight_plan82 = FlightTimeTable("Tokyo", "San Francisco", [flightsList[141], flightsList[142]])
    flight_plan83 = FlightTimeTable("Tokyo", "Shanghai",[flightsList[143], flightsList[144], flightsList[145], flightsList[146]])
    flight_plan84 = FlightTimeTable("Venice", "Rome", [flightsList[147], flightsList[148], flightsList[149]])

    list_of_flight_plans=[]
    list_of_flight_plans.append(flight_plan1)
    list_of_flight_plans.append(flight_plan2)
    list_of_flight_plans.append(flight_plan3)
    list_of_flight_plans.append(flight_plan4)
    list_of_flight_plans.append(flight_plan5)
    list_of_flight_plans.append(flight_plan6)
    list_of_flight_plans.append(flight_plan7)
    list_of_flight_plans.append(flight_plan8)
    list_of_flight_plans.append(flight_plan9)
    list_of_flight_plans.append(flight_plan10)
    list_of_flight_plans.append(flight_plan11)
    list_of_flight_plans.append(flight_plan12)
    list_of_flight_plans.append(flight_plan13)
    list_of_flight_plans.append(flight_plan14)
    list_of_flight_plans.append(flight_plan15)
    list_of_flight_plans.append(flight_plan16)
    list_of_flight_plans.append(flight_plan17)
    list_of_flight_plans.append(flight_plan18)
    list_of_flight_plans.append(flight_plan19)
    list_of_flight_plans.append(flight_plan20)
    list_of_flight_plans.append(flight_plan21)
    list_of_flight_plans.append(flight_plan22)
    list_of_flight_plans.append(flight_plan23)
    list_of_flight_plans.append(flight_plan24)
    list_of_flight_plans.append(flight_plan25)
    list_of_flight_plans.append(flight_plan26)
    list_of_flight_plans.append(flight_plan27)
    list_of_flight_plans.append(flight_plan28)
    list_of_flight_plans.append(flight_plan29)
    list_of_flight_plans.append(flight_plan31)
    list_of_flight_plans.append(flight_plan32)
    list_of_flight_plans.append(flight_plan33)
    list_of_flight_plans.append(flight_plan34)
    list_of_flight_plans.append(flight_plan35)
    list_of_flight_plans.append(flight_plan36)
    list_of_flight_plans.append(flight_plan37)
    list_of_flight_plans.append(flight_plan38)
    list_of_flight_plans.append(flight_plan39)
    list_of_flight_plans.append(flight_plan40)
    list_of_flight_plans.append(flight_plan41)
    list_of_flight_plans.append(flight_plan42)
    list_of_flight_plans.append(flight_plan43)
    list_of_flight_plans.append(flight_plan44)
    list_of_flight_plans.append(flight_plan45)
    list_of_flight_plans.append(flight_plan46)
    list_of_flight_plans.append(flight_plan47)
    list_of_flight_plans.append(flight_plan48)
    list_of_flight_plans.append(flight_plan49)
    list_of_flight_plans.append(flight_plan50)
    list_of_flight_plans.append(flight_plan51)
    list_of_flight_plans.append(flight_plan52)
    list_of_flight_plans.append(flight_plan53)
    list_of_flight_plans.append(flight_plan54)
    list_of_flight_plans.append(flight_plan55)
    list_of_flight_plans.append(flight_plan56)
    list_of_flight_plans.append(flight_plan57)
    list_of_flight_plans.append(flight_plan58)
    list_of_flight_plans.append(flight_plan59)
    list_of_flight_plans.append(flight_plan60)
    list_of_flight_plans.append(flight_plan61)
    list_of_flight_plans.append(flight_plan62)
    list_of_flight_plans.append(flight_plan63)
    list_of_flight_plans.append(flight_plan64)
    list_of_flight_plans.append(flight_plan65)
    list_of_flight_plans.append(flight_plan66)
    list_of_flight_plans.append(flight_plan67)
    list_of_flight_plans.append(flight_plan68)
    list_of_flight_plans.append(flight_plan69)
    list_of_flight_plans.append(flight_plan70)
    list_of_flight_plans.append(flight_plan71)
    list_of_flight_plans.append(flight_plan72)
    list_of_flight_plans.append(flight_plan73)
    list_of_flight_plans.append(flight_plan74)
    list_of_flight_plans.append(flight_plan75)
    list_of_flight_plans.append(flight_plan76)
    list_of_flight_plans.append(flight_plan77)
    list_of_flight_plans.append(flight_plan78)
    list_of_flight_plans.append(flight_plan79)
    list_of_flight_plans.append(flight_plan80)
    list_of_flight_plans.append(flight_plan81)
    list_of_flight_plans.append(flight_plan82)
    list_of_flight_plans.append(flight_plan83)
    list_of_flight_plans.append(flight_plan84)
    return list_of_flight_plans

# this function prints the list of Flights for a FlightTimeTable object
def printFlightsInTimeTable(listOfFlights):
    for flight2 in listOfFlights:
        printFlights2(flight2)
# this function prints a Flights object in the correct order
def printFlights2(flightsList):
    for flight in flightsList:
        print(flight.departure_time , " // " , flight.arrival_time , " // " , flight.flight_number , " // " , flight.list_of_days, "\n")

def printingTimeTable(flight):
        print(flight.departure_city, " , " , flight.arrival_city ,","),printFlights2(flight.list_of_flights)


def getList(listOfflights):
    for i  in listOfflights:
        print(i.departure_time)

def distance(x,y):
    const= 111.2
    z=x-y
    position = abs(z)*const
    return position

